/**
 * Katalog dovedností pro našeptávání (docs/03 §1.2).
 * Vlastní text zůstává povolený — katalog jen napovídá a sjednocuje zápis
 * (důležité pro filtr v adresáři lidí).
 */
export const SKILL_CATEGORIES: { label: string; skills: string[] }[] = [
  {
    label: "Kuchyně",
    skills: [
      "Teplá kuchyně",
      "Studená kuchyně",
      "Minutky",
      "Omáčky",
      "Polévky",
      "Česká klasika",
      "Moderní česká kuchyně",
      "Italská kuchyně",
      "Francouzská kuchyně",
      "Asijská kuchyně",
      "Sous-vide",
      "Gril & BBQ",
      "Fine dining",
      "Plating",
      "Ryby a mořské plody",
      "Bourání masa",
      "Vegetariánská a veganská kuchyně",
      "Bezlepková kuchyně",
      "Fermentace a zavařování",
      "Práce s konvektomatem",
      "Mise en place",
      "Menu development",
      "Kalkulace a food cost",
      "HACCP",
    ],
  },
  {
    label: "Pekárna & cukrárna",
    skills: [
      "Kváskové pečení",
      "Chlebové pečivo",
      "Jemné pečivo",
      "Laminovaná těsta",
      "Entremety",
      "Dorty na zakázku",
      "Dezerty à la carte",
      "Práce s čokoládou",
      "Zmrzlina a sorbety",
    ],
  },
  {
    label: "Bar",
    skills: [
      "Klasické koktejly",
      "Signature drinky",
      "Mixologie",
      "Flair",
      "Práce s ledem",
      "Čepování piva (hladinka, mlíko)",
      "Pivní speciály",
      "Vinný servis",
      "Nealko pairing",
      "Barový sklad a objednávky",
    ],
  },
  {
    label: "Káva",
    skills: [
      "Kalibrace espressa",
      "Latte art",
      "Filtrovaná káva (V60, aeropress)",
      "Cupping",
      "Školení baristů",
    ],
  },
  {
    label: "Servis",
    skills: [
      "Snídaňový servis",
      "À la carte servis",
      "Fine dining servis",
      "Banketový a event servis",
      "Someliérské minimum",
      "Práce s pokladnou / POS",
      "Rezervační systémy",
      "Péče o hosty",
      "Řešení stížností",
      "Upselling",
      "Práce pod tlakem",
    ],
  },
  {
    label: "Vedení & provoz",
    skills: [
      "Vedení směny",
      "Vedení kuchyně",
      "Vedení baru",
      "Nábor a zaučování",
      "Tvorba směn a rozpisů",
      "Objednávky a dodavatelé",
      "Inventury",
      "Skladové hospodářství",
      "Reporting a čísla provozu",
      "Marketing podniku",
      "Sociální sítě podniku",
      "Event management",
      "Catering",
    ],
  },
  {
    label: "Jazyky",
    skills: [
      "Angličtina",
      "Němčina",
      "Francouzština",
      "Španělština",
      "Italština",
      "Ukrajinština",
    ],
  },
  {
    label: "Certifikace & ostatní",
    skills: [
      "Potravinářský průkaz",
      "Hygienické minimum",
      "Barista kurz",
      "Someliér kurz",
      "WSET",
      "První pomoc",
      "Řidičský průkaz B",
    ],
  },
];

export const ALL_SKILLS: string[] = SKILL_CATEGORIES.flatMap((category) => category.skills);
